Repository dasch-swiss/dsp-api, pull requests merged in 2018-03, with the labels that each got.

#758 build (travis): add execution of publish stage when on tag
  .travis.yml
Labels: enhancement, in-progress

#722 Wip/goldbach beta release
  webapi/_test_data/all_data/admin-data.ttl
  webapi/_test_data/all_data/beol-data.ttl
  webapi/_test_data/all_data/biblio-data.ttl
  webapi/_test_data/all_data/permissions-data.ttl
  webapi/_test_data/ontologies/beol-onto.ttl
  webapi/_test_data/ontologies/biblio-onto.ttl
  webapi/_test_data/project_shortcodes.md
  webapi/_test_data/test_route/search/extendedsearchv2.js
  webapi/_test_data/test_route/texts/mappingForLetter.xml
  webapi/scripts/fuseki-load-test-data.sh
  webapi/scripts/graphdb-knora-prod-data.expect
  webapi/scripts/graphdb-knora-test-data.expect
  webapi/src/main/resources/application.conf
  webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala
  webapi/src/main/scala/org/knora/webapi/responders/v1/SipiResponderV1.scala
  webapi/src/main/scala/org/knora/webapi/util/StringFormatter.scala
  webapi/src/test/resources/test-data/ontologyR2RV2/allOntologyMetadata.json
  webapi/src/test/scala/org/knora/webapi/SharedTestDataV1.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec.scala
Labels: API v2, enhancement

#739 add name of a list node to list value
  webapi/_test_data/all_data/anything-data.ttl
  webapi/_test_data/all_data/beol-data.ttl
  webapi/src/main/scala/org/knora/webapi/OntologyConstants.scala
  webapi/src/main/scala/org/knora/webapi/messages/store/triplestoremessages/TriplestoreMessages.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/KnoraResponseV2.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraApiV2WithValueObjects.scala
  webapi/src/main/scala/org/knora/webapi/store/triplestore/http/HttpTriplestoreConnector.scala
  webapi/src/main/scala/org/knora/webapi/util/ConstructResponseUtilV2.scala
  webapi/src/main/twirl/queries/sparql/v2/getResourcePropertiesAndValuesGraphDB.scala.txt
  webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiWithValueObjects.json
  webapi/src/test/resources/test-data/resourcesR2RV2/ThingWithListValue.jsonld
  webapi/src/test/resources/test-data/searchR2RV2/ThingWithBooleanOptional.jsonld
  webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2R2Spec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
Labels: API v2, enhancement

#767 Use types from the triplestore in predicate objects in ontologies
  docs/rst/00-release-notes/v1.3.0.rst
  webapi/src/main/scala/org/knora/webapi/OntologyConstants.scala
  webapi/src/main/scala/org/knora/webapi/messages/store/triplestoremessages/TriplestoreMessages.scala
  webapi/src/main/scala/org/knora/webapi/messages/v1/responder/ontologymessages/OntologyMessagesV1.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraApiV2Simple.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraApiV2WithValueObjects.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
  webapi/src/main/scala/org/knora/webapi/responders/v1/OntologyResponderV1.scala
  webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala
  webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
  webapi/src/main/scala/org/knora/webapi/util/jsonld/JsonLDUtil.scala
  webapi/src/main/twirl/queries/sparql/v2/changeClassLabelsOrComments.scala.txt
  webapi/src/main/twirl/queries/sparql/v2/changePropertyLabelsOrComments.scala.txt
  webapi/src/main/twirl/queries/sparql/v2/createClass.scala.txt
  webapi/src/main/twirl/queries/sparql/v2/generateInsertStatementsForCreateProperty.scala.txt
  webapi/src/main/twirl/queries/sparql/v2/generateInsertStatementsForPredicates.scala.txt
  webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiWithValueObjects.json
  webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiWithValueObjectsHasColor.json
  webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/v2/responder/ontologymessages/InputOntologiesV2Spec.scala
  webapi/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
Labels: bug, enhancement, ready-for-review

#776 fix (beol): add beol project shortcode
  webapi/_test_data/test_route/search/extendedsearchv2.js
Labels: bug

#781 build (travis): fix docker image building
  .travis.yml
Labels: bug

#782 build (salsah1): add bash to final image
  salsah1/Dockerfile
Labels: bug

#775 Generate knora-api ontologies, and convert standoff classes to external schemas
  docs/rst/03-knora-api-server/api_v2/ontology-information.rst
  knora-ontologies/knora-base.ttl
  webapi/_test_data/ontologies/incunabula-onto.ttl
  webapi/src/main/scala/org/knora/webapi/OntologyConstants.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/KnoraResponseV2.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraApiV2Simple.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraApiV2WithValueObjects.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
  webapi/src/main/scala/org/knora/webapi/responders/v1/StandoffResponderV1.scala
  webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
  webapi/src/main/scala/org/knora/webapi/util/ConstructResponseUtilV2.scala
  webapi/src/main/scala/org/knora/webapi/util/StringFormatter.scala
  webapi/src/main/scala/org/knora/webapi/util/search/v2/ExplicitTypeInspectorV2.scala
  webapi/src/test/resources/test-data/ontologyR2RV2/bildSimple.json
  webapi/src/test/resources/test-data/ontologyR2RV2/bildWithValueObjects.json
  webapi/src/test/resources/test-data/ontologyR2RV2/imagesOntologySimple.json
  webapi/src/test/resources/test-data/ontologyR2RV2/imagesOntologyWithValueObjects.json
  webapi/src/test/resources/test-data/ontologyR2RV2/incunabulaOntologySimple.json
  webapi/src/test/resources/test-data/ontologyR2RV2/incunabulaOntologyWithValueObjects.json
  webapi/src/test/resources/test-data/ontologyR2RV2/incunabulaPageAndBookWithValueObjects.json
  webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiDate.json
  webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiDateValue.json
  webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiOntologySimple.json
  webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiSimpleHasColor.json
  webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiWithValueObjects.json
  webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiWithValueObjectsHasColor.json
  webapi/src/test/resources/test-data/ontologyR2RV2/standoffOntologySimple.json
  webapi/src/test/resources/test-data/ontologyR2RV2/standoffOntologyWithValueObjects.json
  webapi/src/test/resources/test-data/resourcesR2RV2/ThingWithListValue.jsonld
  webapi/src/test/resources/test-data/searchR2RV2/bookWithIncomingPagesOnlyLink.jsonld
  webapi/src/test/resources/test-data/searchR2RV2/bookWithIncomingPagesWithAllRequestedProps.jsonld
  webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/ResponseCheckerR2RV2.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/responders/v1/OntologyResponderV1Spec.scala
Labels: API v2, breaking (salsah2), enhancement, ready-for-review

#784 KnarQL: query label of a list node for a list value
  webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala
  webapi/src/test/resources/test-data/searchR2RV2/ThingWithListValue.jsonld
  webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
Labels: API v2, bug
