Repository dasch-swiss/dsp-api, pull requests merged in 2018-04, with the labels that each got.

#801 Bug/search list
  docs/rst/00-release-notes/v1.4.0.rst
  webapi/_test_data/all_data/anything-data.ttl
  webapi/src/main/twirl/queries/sparql/v1/searchExtendedGraphDB.scala.txt
  webapi/src/test/resources/test-data/searchR2RV2/ThingWithBooleanOptional.jsonld
  webapi/src/test/resources/test-data/searchR2RV2/ThingWithListValue.jsonld
  webapi/src/test/scala/org/knora/webapi/e2e/v1/SearchV1R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
Labels: API v1, breaking, bug, ready-for-review

#809 build (webapi): fix path to salsah1
  docs/Makefile
Labels: bug

#817 Fix image orientation in SALSAH 1 (moved from #768)
  docs/rst/00-release-notes/v1.4.0.rst
  salsah1/src/public/js/imagebase.js
  salsah1/src/public/js/jquery.location.js
Labels: bug

#815 feature (webapi): allow changing of user’s password by system admin
  webapi/WebapiBuild.sbt
  webapi/src/main/scala/org/knora/webapi/messages/admin/responder/usersmessages/UsersMessagesADM.scala
  webapi/src/main/scala/org/knora/webapi/responders/admin/UsersResponderADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/Authenticator.scala
  webapi/src/main/scala/org/knora/webapi/routing/RejectingRoute.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/UsersRouteADM.scala
  webapi/src/test/resources/logback-test.xml
  webapi/src/test/scala/org/knora/webapi/e2e/admin/UsersADME2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/responders/admin/UsersResponderADMSpec.scala
Labels: API admin, enhancement, ready-for-review

#806 Validate ontologies loaded from the triplestore
  docs/rst/00-release-notes/v1.4.0.rst
  docs/rst/02-knora-ontologies/knora-base.rst
  docs/rst/03-knora-api-server/api_v2/ontology-information.rst
  knora-ontologies/knora-admin.ttl
  knora-ontologies/knora-base.ttl
  knora-ontologies/salsah-gui.ttl
  webapi/WebapiBuild.sbt
  webapi/_test_data/ontologies/anything-onto.ttl
  webapi/_test_data/ontologies/biblio-onto.ttl
  webapi/_test_data/other.v1.DrawingsGodsV1E2ESpec/rvp-admin-data.ttl
  webapi/_test_data/other.v1.DrawingsGodsV1Spec/drawings-gods_admin-data.ttl
  webapi/_test_data/other.v1.DrawingsGodsV1Spec/drawings-gods_ontology.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/cardinality-with-guiattribute-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/cardinality-with-guielement-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/class-incompatible-with-scc-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/class-with-cardinality-on-kbhasvalue-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/class-with-cardinality-on-kbresprop-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/class-with-misdefined-link-property-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/class-with-misdefined-link-value-property-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/class-with-missing-property-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/class-with-non-resource-prop-cardinality-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/class-without-label-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/filevalue-prop-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/missing-link-cardinality-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/missing-link-value-cardinality-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/onto-without-project.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/prop-both-value-and-link-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/prop-with-guielement-scc-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/prop-with-guiorder-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/prop-with-incompatible-occ-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/prop-with-non-knora-occ-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/prop-with-non-knora-scc-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/prop-with-value-scc-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/property-without-label-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/resource-class-is-standoff-class-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/resource-class-with-invalid-base-class-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/resource-prop-without-label-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/resource-prop-without-occ-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/resource-prop-wrong-base-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/standoff-class-with-invalid-base-class-onto.ttl
  webapi/_test_data/responders.v2.OntologyResponderV2Spec/standoff-class-with-resprop-cardinality-onto.ttl
  webapi/src/main/scala/org/knora/webapi/KnoraService.scala
  webapi/src/main/scala/org/knora/webapi/OntologyConstants.scala
  webapi/src/main/scala/org/knora/webapi/http/CORSSupport.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/KnoraApiV2WithValueObjects.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
  webapi/src/main/scala/org/knora/webapi/responders/v2/OntologyResponderV2.scala
  webapi/src/main/scala/org/knora/webapi/util/StatementCollectingHandler.scala
  webapi/src/main/scala/org/knora/webapi/util/StringFormatter.scala
  webapi/src/main/scala/org/knora/webapi/util/TransformData.scala
  webapi/src/main/scala/org/knora/webapi/util/TransformOntology.scala
  webapi/src/main/scala/org/knora/webapi/util/search/v2/SearchParserV2.scala
  webapi/src/main/twirl/queries/sparql/v2/changeClassLabelsOrComments.scala.txt
  webapi/src/main/twirl/queries/sparql/v2/changePropertyLabelsOrComments.scala.txt
  webapi/src/test/resources/test-data/ontologyR2RV2/knoraApiWithValueObjects.json
  webapi/src/test/resources/test-data/ontologyR2RV2/salsahGuiOntology.json
  webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/responders/v2/OntologyResponderV2Spec.scala
Labels: enhancement, ready-for-review

#836 docs (webapi): add missing release notes entry
  .gitignore
  .travis.yml
  docs/DocsBuild.sbt
  docs/src/jekyll/index.md
  docs/src/sphinx/00-release-notes/v1.4.0.rst
  webapi/WebapiBuild.sbt
Labels: enhancement

#838 build (webapi): releasing v1.4.0
  RELEASING.md
  docs/DocsBuild.sbt
  docs/src/paradox/00-release-notes/index.md
  docs/src/paradox/00-release-notes/v1.4.0.md
  docs/src/paradox/00-release-notes/v1.5.0.md
  docs/src/sphinx/00-release-notes/index.rst
  docs/src/sphinx/00-release-notes/v1.1.0.rst
  docs/src/sphinx/00-release-notes/v1.2.0.rst
  docs/src/sphinx/00-release-notes/v1.3.0.rst
  docs/src/sphinx/00-release-notes/v1.4.0.rst
  salsah1/SalsahBuild.sbt
  webapi/WebapiBuild.sbt
Labels: enhancement
