Repository dasch-swiss/dsp-api, pull requests merged in 2020-07, with the labels that each got.

#1666 Fix gren issue in github actions workflow
  .github/workflows/main.yml
Labels: chore

#1669 fix: loading of data (DSP-445)
  KnoraBuild.sbt
  Makefile
  webapi/scripts/fuseki-ci-prepare.sh
  webapi/scripts/fuseki-dump-repository.sh
  webapi/scripts/fuseki-functions.sh
  webapi/scripts/fuseki-init-knora-test-minimal.sh
  webapi/scripts/fuseki-init-knora-test-unit-minimal.sh
  webapi/scripts/fuseki-init-knora-test-unit.sh
  webapi/scripts/fuseki-init-knora-test.sh
  webapi/scripts/fuseki-knora-test-unit-repository-config.ttl
  webapi/scripts/fuseki-repository-config.ttl.template
  webapi/src/main/scala/org/knora/webapi/store/triplestore/http/HttpTriplestoreConnector.scala
Labels: bug

#1677 Refactor Tests
  docs/03-apis/api-admin/groups.md
  docs/03-apis/api-admin/lists.md
  docs/03-apis/api-admin/projects.md
  docs/03-apis/api-admin/users.md
  webapi/src/main/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsMessagesADM.scala
  webapi/src/test/scala/org/knora/webapi/e2e/admin/GroupsADME2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/admin/ListsADME2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/admin/ProjectsADME2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/admin/UsersADME2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/messages/admin/responder/groupsmessages/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/messages/admin/responder/groupsmessages/GroupsMessagesADMSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/admin/responder/listsmessages/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADMSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/admin/responder/permissionsmessages/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/messages/admin/responder/projectsmessages/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsMessagesADMSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/admin/responder/usersmessages/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/messages/admin/responder/usersmessages/UsersMessagesADMSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/store/triplestoremessages/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/messages/v1/responder/permissionmessages/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/messages/v1/responder/usermessages/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/messages/v2/responder/ontologymessages/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/other/v1/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/other/v2/BUILD.bazel
Labels: testing

#1680 build: bump rules_docker and instructions for installing bazelisk
  .bazelversion
  .github/workflows/main.yml
  README.md
  WORKSPACE
  docker/knora-salsah1/BUILD.bazel
  docs/05-internals/development/bazel.md
Labels: build, chore
