Repository dasch-swiss/dsp-api, pull requests merged in 2020-11, with the labels that each got.

#1747 DSP-920 Renaming default github branch to "main" ; Move to the same base branch
  .github/workflows/main.yml
  README.md
  RELEASING.md
  docs/04-publishing-deployment/publishing.md
  docs/05-internals/development/docker-compose.md
  docs/05-internals/development/graphdb.md
  docs/05-internals/development/overview.md
  docs/07-sipi/setup-sipi-for-knora.md
  sipi/README.md
Labels: chore

#1742 feat: Add feature toggles (DSP-910)
  docs/03-apis/feature-toggles.md
  docs/03-apis/index.md
  docs/05-internals/design/api-v2/how-to-add-a-route.md
  docs/05-internals/design/principles/feature-toggles.md
  docs/05-internals/design/principles/index.md
  third_party/dependencies.bzl
  webapi/src/main/resources/application.conf
  webapi/src/main/scala/org/knora/webapi/app/ApplicationActor.scala
  webapi/src/main/scala/org/knora/webapi/exceptions/Exceptions.scala
  webapi/src/main/scala/org/knora/webapi/feature/BUILD.bazel
  webapi/src/main/scala/org/knora/webapi/feature/FeatureFactory.scala
  webapi/src/main/scala/org/knora/webapi/http/version/ServerVersion.scala
  webapi/src/main/scala/org/knora/webapi/messages/admin/responder/sipimessages/SipiMessagesADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/BUILD.bazel
  webapi/src/main/scala/org/knora/webapi/routing/HealthRoute.scala
  webapi/src/main/scala/org/knora/webapi/routing/KnoraRoute.scala
  webapi/src/main/scala/org/knora/webapi/routing/RejectingRoute.scala
  webapi/src/main/scala/org/knora/webapi/routing/RouteUtilADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/RouteUtilV2.scala
  webapi/src/main/scala/org/knora/webapi/routing/SwaggerApiDocsRoute.scala
  webapi/src/main/scala/org/knora/webapi/routing/VersionRoute.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/GroupsRouteADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/ListsRouteADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/PermissionsRouteADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/SipiRouteADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/StoreRouteADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/UsersRouteADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/lists/ListsRouteADMFeatureFactory.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/lists/NewListsRouteADMFeature.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/lists/OldListsRouteADMFeature.scala
  webapi/src/main/scala/org/knora/webapi/routing/v1/AssetsRouteV1.scala
  webapi/src/main/scala/org/knora/webapi/routing/v1/AuthenticationRouteV1.scala
  webapi/src/main/scala/org/knora/webapi/routing/v1/CkanRouteV1.scala
  webapi/src/main/scala/org/knora/webapi/routing/v1/ListsRouteV1.scala
  webapi/src/main/scala/org/knora/webapi/routing/v1/ProjectsRouteV1.scala
  webapi/src/main/scala/org/knora/webapi/routing/v1/ResourceTypesRouteV1.scala
  webapi/src/main/scala/org/knora/webapi/routing/v1/ResourcesRouteV1.scala
  webapi/src/main/scala/org/knora/webapi/routing/v1/SearchRouteV1.scala
  webapi/src/main/scala/org/knora/webapi/routing/v1/StandoffRouteV1.scala
  webapi/src/main/scala/org/knora/webapi/routing/v1/UsersRouteV1.scala
  webapi/src/main/scala/org/knora/webapi/routing/v1/ValuesRouteV1.scala
  webapi/src/main/scala/org/knora/webapi/routing/v2/AuthenticationRouteV2.scala
  webapi/src/main/scala/org/knora/webapi/routing/v2/ListsRouteV2.scala
  webapi/src/main/scala/org/knora/webapi/routing/v2/MetadataRouteV2.scala
  webapi/src/main/scala/org/knora/webapi/routing/v2/OntologiesRouteV2.scala
  webapi/src/main/scala/org/knora/webapi/routing/v2/ResourcesRouteV2.scala
  webapi/src/main/scala/org/knora/webapi/routing/v2/SearchRouteV2.scala
  webapi/src/main/scala/org/knora/webapi/routing/v2/StandoffRouteV2.scala
  webapi/src/main/scala/org/knora/webapi/routing/v2/ValuesRouteV2.scala
  webapi/src/main/scala/org/knora/webapi/settings/KnoraSettings.scala
  webapi/src/main/scala/org/knora/webapi/store/triplestore/TriplestoreManager.scala
  webapi/src/main/scala/org/knora/webapi/store/triplestore/http/HttpTriplestoreConnector.scala
  webapi/src/test/scala/org/knora/webapi/E2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/e2e/FeatureToggleR2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/http/ServerVersionE2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/http/version/ServerVersionSpec.scala
Labels: API/Admin, API/V2, enhancement

#1750 Update README.md
  README.md
Labels: chore

#1755 DSP-1029: Add the missing dependency
  webapi/src/main/scala/org/knora/webapi/messages/BUILD.bazel
Labels: bug

#1757 build: bazel workspace cleanup
  WORKSPACE
  toolchains/BUILD.bazel
Labels: chore

#1758 feat(api-v2): Control JSON-LD nesting via an HTTP header (DSP-1084)
  docs/03-apis/api-v2/introduction.md
  test_data/metadataE2EV2/metadata-flat.jsonld
  test_data/metadataE2EV2/metadata.ttl
  webapi/src/main/scala/org/knora/webapi/OntologySchema.scala
  webapi/src/main/scala/org/knora/webapi/http/handler/KnoraExceptionHandler.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/rdf/JsonLDUtil.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/rdf/RdfFormatUtil.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/KnoraRequestV2.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/KnoraResponseV2.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/ResourceMessagesV2.scala
  webapi/src/main/scala/org/knora/webapi/routing/RouteUtilV2.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/MetadataRouteV2E2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/JsonLDUtilSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/KnoraResponseV2Spec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/RdfFormatUtilSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/jenaimpl/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/rdf4jimpl/BUILD.bazel
Labels: API/V2, enhancement
