Repository dasch-swiss/dsp-api, pull requests merged in 2020-12, with the labels that each got.

#1762 feat(rdf-api): Add a general-purpose SHACL validation utility (DSP-930)
  docs/05-internals/design/principles/rdf-api.md
  test_data/shacl/test/person.ttl
  third_party/dependencies.bzl
  webapi/BUILD.bazel
  webapi/src/it/scala/org/knora/webapi/ITKnoraFakeSpec.scala
  webapi/src/it/scala/org/knora/webapi/ITKnoraLiveSpec.scala
  webapi/src/main/resources/application.conf
  webapi/src/main/scala/org/knora/webapi/app/LiveCore.scala
  webapi/src/main/scala/org/knora/webapi/messages/BUILD.bazel
  webapi/src/main/scala/org/knora/webapi/messages/OntologyConstants.scala
  webapi/src/main/scala/org/knora/webapi/messages/StringFormatter.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/rdf/AbstractShaclValidator.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/rdf/RdfFeatureFactory.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/rdf/RdfFormatUtil.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/rdf/RdfModel.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/rdf/ShaclValidator.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/rdf/jenaimpl/JenaShaclValidator.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/rdf/rdf4jimpl/RDF4JShaclValidator.scala
  webapi/src/main/scala/org/knora/webapi/settings/KnoraSettings.scala
  webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/RepositoryUpdater.scala
  webapi/src/test/scala/org/knora/webapi/CoreSpec.scala
  webapi/src/test/scala/org/knora/webapi/E2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/JsonLDUtilSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/RdfFormatUtilSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/ShaclValidatorSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/jenaimpl/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/jenaimpl/JenaShaclValidatorSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/rdf4jimpl/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/rdf4jimpl/RDF4JShaclValidatorSpec.scala
Labels: API/V2, enhancement

#1764 DSP-1033 Reposition List Nodes
  docs/03-apis/api-admin/lists.md
  docs/03-apis/api-admin/lists_new-list-admin-routes_v1.md
  test_data/all_data/anything-data.ttl
  webapi/scripts/expected-client-test-data.txt
  webapi/src/main/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADM.scala
  webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/lists/NewListsRouteADMFeature.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/lists/updateListItemsRouteADM.scala
  webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/changeParentNode.scala.txt
  webapi/src/test/scala/org/knora/webapi/e2e/admin/lists/DeleteListItemsRouteADME2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/admin/lists/UpdateListItemsRouteADME2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADMSpec.scala
  webapi/src/test/scala/org/knora/webapi/responders/admin/ListsResponderADMSpec.scala
Labels: enhancement

#1767 enhancement(triplestore): Use N-Quads instead of TriG for repository upgrade (DSP-1129)
  docs/05-internals/development/updating-repositories.md
  test_data/rdfFormatUtil/BookReiseInsHeiligeLand.nq
  test_data/rdfFormatUtil/BookReiseInsHeiligeLand.trig
  webapi/src/main/scala/org/knora/webapi/RdfMediaTypes.scala
  webapi/src/main/scala/org/knora/webapi/messages/store/triplestoremessages/TriplestoreMessages.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/rdf/JsonLDUtil.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/rdf/RdfFeatureFactory.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/rdf/RdfFormatUtil.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/rdf/jenaimpl/JenaFormatUtil.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/rdf/rdf4jimpl/RDF4JFormatUtil.scala
  webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala
  webapi/src/main/scala/org/knora/webapi/store/triplestore/http/HttpTriplestoreConnector.scala
  webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/RepositoryUpdater.scala
  webapi/src/test/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsMessagesADMSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/JsonLDUtilSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/RdfFormatUtilSpec.scala
Labels: enhancement

#1763 fix(sipi): Don't expect API v1 status code (DSP-1114)
  salsah1/src/test/scala/org/knora/salsah/TestContainers.scala
  sipi/config/BUILD.bazel
  sipi/config/sipi.knora-docker-config.lua
  sipi/config/sipi.knora-docker-no-auth-config.lua
  sipi/config/sipi.knora-docker-test-config.lua
  sipi/config/sipi.knora-local-config.lua
  sipi/scripts/sipi.init-knora-no-auth.lua
  sipi/scripts/sipi.init-knora-test.lua
  sipi/scripts/sipi.init-knora.lua
  webapi/src/it/scala/org/knora/webapi/TestContainers.scala
  webapi/src/it/scala/org/knora/webapi/e2e/v2/KnoraSipiIntegrationV2ITSpec.scala
  webapi/src/main/scala/org/knora/webapi/messages/admin/responder/sipimessages/SipiMessagesADM.scala
  webapi/src/main/scala/org/knora/webapi/responders/admin/SipiResponderADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/SipiRouteADM.scala
  webapi/src/test/scala/org/knora/webapi/TestContainers.scala
Labels: Sipi, bug

#1765 DSP-1094 Upgrade Swagger version
  third_party/dependencies.bzl
  third_party/versions.bzl
  webapi/BUILD.bazel
  webapi/src/main/scala/org/knora/webapi/app/ApplicationActor.scala
  webapi/src/main/scala/org/knora/webapi/app/BUILD.bazel
  webapi/src/main/scala/org/knora/webapi/http/BUILD.bazel
  webapi/src/main/scala/org/knora/webapi/http/directives/BUILD.bazel
  webapi/src/main/scala/org/knora/webapi/http/directives/DSPApiDirectives.scala
  webapi/src/test/scala/org/knora/webapi/e2e/FeatureToggleR2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v1/StandoffV1R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v1/ValuesV1R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
Labels: chore

#1768 DSP-1106 Update Permission
  docs/03-apis/api-admin/permissions.md
  webapi/scripts/expected-client-test-data.txt
  webapi/src/main/scala/org/knora/webapi/messages/OntologyConstants.scala
  webapi/src/main/scala/org/knora/webapi/messages/admin/responder/permissionsmessages/PermissionsMessagesADM.scala
  webapi/src/main/scala/org/knora/webapi/responders/admin/PermissionsResponderADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/PermissionsRouteADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/lists/UpdateListItemsRouteADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/permissions/CreatePermissionRouteADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/permissions/GetPermissionsRouteADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/permissions/UpdatePermissionRouteADM.scala
  webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/createNewAdministrativePermission.scala.txt
  webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/createNewDefaultObjectAccessPermission.scala.txt
  webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/getPermissionByIRI.scala.txt
  webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/updatePermission.scala.txt
  webapi/src/test/scala/org/knora/webapi/e2e/admin/PermissionsADME2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/admin/responder/permissionsmessages/PermissionsMessagesADMSpec.scala
  webapi/src/test/scala/org/knora/webapi/responders/admin/PermissionsResponderADMSpec.scala
Labels: API/Admin, enhancement

#1770 refactor: Use java.nio.file.Path instead of java.io.File (DSP-1124)
  webapi/src/it/scala/org/knora/webapi/ITKnoraLiveSpec.scala
  webapi/src/it/scala/org/knora/webapi/e2e/v1/KnoraSipiIntegrationV1ITSpec.scala
  webapi/src/it/scala/org/knora/webapi/e2e/v2/KnoraSipiIntegrationV2ITSpec.scala
  webapi/src/main/scala/org/knora/webapi/contributors/GenerateContributorsFile.scala
  webapi/src/main/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsMessagesADM.scala
  webapi/src/main/scala/org/knora/webapi/messages/store/triplestoremessages/TriplestoreMessages.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/FakeTriplestore.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/rdf/AbstractShaclValidator.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/rdf/JsonLDUtil.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/rdf/RdfFormatUtil.scala
  webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/ProjectsRouteADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/v1/AssetsRouteV1.scala
  webapi/src/main/scala/org/knora/webapi/settings/KnoraSettings.scala
  webapi/src/main/scala/org/knora/webapi/store/triplestore/embedded/JenaTDBActor.scala
  webapi/src/main/scala/org/knora/webapi/store/triplestore/http/HttpTriplestoreConnector.scala
  webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/RepositoryUpdater.scala
  webapi/src/main/scala/org/knora/webapi/util/FileUtil.scala
  webapi/src/test/scala/org/knora/webapi/E2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/contributors/GenerateContributorsFileSpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/InstanceCheckerSpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v1/SipiV1R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v1/StandoffV1R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/JSONLDHandlingV2R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/ListsRouteV2R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/MetadataRouteV2E2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/ResponseCheckerV2Spec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/StandoffRouteV2R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/ValuesRouteV2E2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/ConstructResponseUtilV2Spec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/JsonLDUtilSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/KnoraResponseV2Spec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/RdfFormatUtilSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/standoff/XMLUtilSpec.scala
  webapi/src/test/scala/org/knora/webapi/responders/v1/ResourcesResponderV1SpecContextData.scala
Labels: chore

#1771 docs: Update README (DSP-1142)
  README.md
  docs/05-internals/development/figures/setting-tab-space.png
  docs/05-internals/development/figures/setup_formatting.png
  docs/05-internals/development/intellij-config.md
Labels: documentation

#1772 chore(rdf-api): Use the Jena RDF API implementation by default (DSP-1153)
  docs/05-internals/design/principles/rdf-api.md
  webapi/src/main/resources/application.conf
  webapi/src/main/scala/org/knora/webapi/messages/util/rdf/jenaimpl/JenaModel.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/rdf/RdfModelSpec.scala
  webapi/src/test/scala/org/knora/webapi/store/triplestore/upgrade/plugins/UpgradePluginPR1307Spec.scala
  webapi/src/test/scala/org/knora/webapi/store/triplestore/upgrade/plugins/UpgradePluginPR1372Spec.scala
  webapi/src/test/scala/org/knora/webapi/store/triplestore/upgrade/plugins/UpgradePluginPR1615Spec.scala
  webapi/src/test/scala/org/knora/webapi/store/triplestore/upgrade/plugins/UpgradePluginSpec.scala
Labels: chore

#1761 DSP-1099 Update Bazel maven rules to see if it fixes problems with macOS Big Sur
  .bazelversion
  WORKSPACE
  docs/05-internals/development/third-party.md
Labels: chore

#1773 DSP-667 CI is failing to test upgrade correctly
  Makefile
  webapi/BUILD.bazel
  webapi/src/it/resources/BUILD.bazel
  webapi/src/it/resources/fuseki.conf
  webapi/src/it/resources/graphdb-free.conf
  webapi/src/it/resources/graphdb-se.conf
  webapi/src/it/resources/logback-test.xml
  webapi/src/it/resources/test.conf
  webapi/src/it/scala/org/knora/webapi/TestContainers.scala
  webapi/src/it/scala/org/knora/webapi/e2e/v1/ErrorV1ITSpec.scala
  webapi/src/it/scala/org/knora/webapi/e2e/v1/KnoraSipiScriptsV1ITSpec.scala
  webapi/src/it/scala/org/knora/webapi/util/MutableTestIri.scala
  webapi/src/it/scala/org/knora/webapi/util/StartupUtils.scala
  webapi/src/test/scala/org/knora/webapi/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/ITKnoraFakeSpec.scala
  webapi/src/test/scala/org/knora/webapi/ITKnoraLiveSpec.scala
  webapi/src/test/scala/org/knora/webapi/KnoraFakeCore.scala
  webapi/src/test/scala/org/knora/webapi/TestContainers.scala
  webapi/src/test/scala/org/knora/webapi/it/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/it/VersionRouteITSpec.scala
  webapi/src/test/scala/org/knora/webapi/it/v1/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/it/v1/DrawingsGodsV1ITSpec.scala
  webapi/src/test/scala/org/knora/webapi/it/v1/ErrorV1ITSpec.scala
  webapi/src/test/scala/org/knora/webapi/it/v1/KnoraSipiIntegrationV1ITSpec.scala
  webapi/src/test/scala/org/knora/webapi/it/v1/KnoraSipiPermissionsV1ITSpec.scala
  webapi/src/test/scala/org/knora/webapi/it/v2/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/it/v2/KnoraSipiIntegrationV2ITSpec.scala
Labels: chore

#1774 fix(upgrade): Fix log output (DSP-1171)
  webapi/src/main/scala/org/knora/webapi/store/triplestore/upgrade/RepositoryUpdater.scala
Labels: bug
