Repository dasch-swiss/dsp-api, pull requests merged in 2020-06, with the labels that each got.

#1651 ConstructResponseUtilV2: Add Tests to Spec
  webapi/src/test/resources/test-data/constructResponseUtilV2/mainQuery1.ttl
  webapi/src/test/resources/test-data/constructResponseUtilV2/mainQuery2.ttl
  webapi/src/test/resources/test-data/constructResponseUtilV2/thingWithOneHiddenThing.ttl
  webapi/src/test/resources/test-data/constructResponseUtilV2/thingWithStandoff.ttl
  webapi/src/test/resources/test-data/constructResponseUtilV2/visibleThingWithHiddenIntValues.ttl
  webapi/src/test/scala/org/knora/webapi/util/ConstructResponseUtilV2Spec.scala
  webapi/src/test/scala/org/knora/webapi/util/ConstructResponseUtilV2SpecFullData.scala
Labels: API/V2, testing

#1621 fixing typos for list rendering
  docs/src/paradox/03-apis/api-admin/projects.md
Labels: documentation, stage/code-review

#1661 Automated release notes
  .github/workflows/main.yml
  .grenrc
Labels: chore

#1662 Publish on release only
  .github/workflows/main.yml
Labels: chore

#1663 build: add support for SIPI v3.0.0-rc.3 (DSP-433)
  KnoraBuild.sbt
  Makefile
  docker/knora-assets.dockerfile
  docker/knora-sipi.template.dockerfile
  docker/knora-upgrade.dockerfile
  docs/src/paradox/07-sipi/sipi-and-knora.md
  project/Dependencies.scala
  salsah1/src/typescript_interfaces/sampleRequests/sampleChangeValues.ts
  salsah1/src/typescript_interfaces/sampleRequests/sampleResourceResponses.ts
  sipi/Makefile
  sipi/docker-compose.yml
  sipi/images/thumbs/.gitignore
  sipi/images/thumbs/2E8F4aDodnf-Br4rVn1d4FG.jpg
  sipi/images/thumbs/6JU4IuzMr7N-GA9F2syJysr.jpg
  sipi/images/thumbs/7vWhcdvCs5h-CCyR8SxDqDV.jpg
  sipi/images/thumbs/E9wuATEYjXt-BKQrZeu7goo.jpg
  sipi/images/thumbs/G1DWNcSWS59-BPLOBsPeafX.jpg
  sipi/scripts/make_thumbnail.lua
  sipi/server/test.html
  vars.mk
  webapi/src/it/scala/org/knora/webapi/e2e/v1/KnoraSipiScriptsV1ITSpec.scala
  webapi/src/it/scala/org/knora/webapi/e2e/v2/KnoraSipiIntegrationV2ITSpec.scala
  webapi/src/main/scala/org/knora/webapi/responders/v1/ValueUtilV1.scala
Labels: enhancement

#1233 feat(api-v1): Change API v1 file uploads to work like API v2
  README.md
  docs/src/paradox/00-release-notes/next.md
  docs/src/paradox/03-apis/api-v1/adding-resources.md
  docs/src/paradox/03-apis/api-v1/changing-values.md
  docs/src/paradox/03-apis/api-v2/editing-values.md
  docs/src/paradox/05-internals/design/api-v2/sipi.md
  docs/src/paradox/07-sipi/setup-sipi-for-knora.md
  docs/src/paradox/07-sipi/sipi-and-knora.md
  salsah1/src/public/index.html
  salsah1/src/public/js/jquery.location.js
  salsah1/src/public/js/jquery.propedit.js
  salsah1/src/public/js/jquery.resadd.js
  salsah1/src/typescript_interfaces/basicMessageComponents.ts
  salsah1/src/typescript_interfaces/sampleRequests/sampleChangeValues.ts
  salsah1/src/typescript_interfaces/sampleRequests/sampleCreateResources.ts
  sipi/config/sipi.knora-docker-config.lua
  sipi/config/sipi.knora-docker-no-auth-config.lua
  sipi/config/sipi.knora-docker-test-config.lua
  sipi/config/sipi.knora-local-config.lua
  sipi/docker-compose.yml
  sipi/scripts/convert_from_file.lua
  sipi/scripts/convert_from_path.lua
  sipi/scripts/get_knora_session.lua
  sipi/scripts/jwt.lua
  sipi/scripts/make_thumbnail.lua
  sipi/scripts/upload.lua
  webapi/src/it/scala/org/knora/webapi/ITKnoraLiveSpec.scala
  webapi/src/it/scala/org/knora/webapi/e2e/v1/KnoraSipiIntegrationV1ITSpec.scala
  webapi/src/it/scala/org/knora/webapi/e2e/v1/KnoraSipiScriptsV1ITSpec.scala
  webapi/src/it/scala/org/knora/webapi/e2e/v2/KnoraSipiIntegrationV2ITSpec.scala
  webapi/src/it/scala/org/knora/webapi/other/v1/DrawingsGodsV1ITSpec.scala
  webapi/src/main/resources/application.conf
  webapi/src/main/resources/knoraXmlImport.xsd
  webapi/src/main/scala/org/knora/webapi/KnoraSettings.scala
  webapi/src/main/scala/org/knora/webapi/messages/store/sipimessages/SipiMessages.scala
  webapi/src/main/scala/org/knora/webapi/messages/v1/responder/resourcemessages/ResourceMessagesV1.scala
  webapi/src/main/scala/org/knora/webapi/messages/v1/responder/valuemessages/ValueMessagesV1.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
  webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala
  webapi/src/main/scala/org/knora/webapi/responders/v1/ValueUtilV1.scala
  webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala
  webapi/src/main/scala/org/knora/webapi/responders/v2/ResourceUtilV2.scala
  webapi/src/main/scala/org/knora/webapi/routing/v1/ResourcesRouteV1.scala
  webapi/src/main/scala/org/knora/webapi/routing/v1/ValuesRouteV1.scala
  webapi/src/main/scala/org/knora/webapi/store/iiif/SipiConnector.scala
  webapi/src/main/scala/org/knora/webapi/util/StringFormatter.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v1/SipiV1R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/responders/v1/ResourcesResponderV1Spec.scala
  webapi/src/test/scala/org/knora/webapi/responders/v1/ValuesResponderV1Spec.scala
  webapi/src/test/scala/org/knora/webapi/store/iiif/MockSipiConnector.scala
  webapi/src/test/scala/org/knora/webapi/util/StringFormatterSpec.scala
Labels: API/V1, Sipi, breaking, bulk-import
