Repository dasch-swiss/dsp-api, pull requests merged in 2020-10, with the labels that each got.

#1723 chore(build): Bump testcontainers version (DSP-755)
  third_party/dependencies.bzl
Labels: bug, chore

#1725 docs: Update required mkdocs package
  docs/requirements.txt
  mkdocs.yml
Labels: documentation

#1726 PersmissionsDocs: remove the attribute
  docs/03-apis/api-admin/permissions.md
Labels: API/Admin, documentation

#1722 feat(api-v1): Change API v1 file uploads to work like API v2 (DSP-41, PR 3)
  docs/03-apis/api-v1/adding-resources.md
  docs/03-apis/api-v1/changing-values.md
  docs/03-apis/api-v2/editing-values.md
  docs/05-internals/design/api-v2/sipi.md
  docs/07-sipi/setup-sipi-for-knora.md
  docs/07-sipi/sipi-and-knora.md
  docs/src/api-v1/basicMessageComponents.ts
  docs/src/api-v1/sampleRequests/sampleChangeValues.ts
  docs/src/api-v1/sampleRequests/sampleCreateResources.ts
  salsah1/public/index.html
  salsah1/public/js/jquery.location.js
  salsah1/public/js/jquery.propedit.js
  salsah1/public/js/jquery.resadd.js
  sipi/config/sipi.knora-docker-config.lua
  sipi/config/sipi.knora-docker-no-auth-config.lua
  sipi/config/sipi.knora-docker-test-config.lua
  sipi/config/sipi.knora-local-config.lua
  sipi/scripts/convert_from_file.lua
  sipi/scripts/convert_from_path.lua
  sipi/scripts/get_knora_session.lua
  sipi/scripts/jwt.lua
  sipi/scripts/make_thumbnail.lua
  sipi/scripts/upload.lua
  webapi/src/it/scala/org/knora/webapi/ITKnoraLiveSpec.scala
  webapi/src/it/scala/org/knora/webapi/e2e/v1/KnoraSipiIntegrationV1ITSpec.scala
  webapi/src/it/scala/org/knora/webapi/e2e/v1/KnoraSipiScriptsV1ITSpec.scala
  webapi/src/it/scala/org/knora/webapi/e2e/v2/KnoraSipiIntegrationV2ITSpec.scala
  webapi/src/it/scala/org/knora/webapi/other/v1/DrawingsGodsV1ITSpec.scala
  webapi/src/main/resources/application.conf
  webapi/src/main/resources/knoraXmlImport.xsd
  webapi/src/main/scala/org/knora/webapi/messages/StringFormatter.scala
  webapi/src/main/scala/org/knora/webapi/messages/store/sipimessages/SipiMessages.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/ValueUtilV1.scala
  webapi/src/main/scala/org/knora/webapi/messages/v1/responder/resourcemessages/ResourceMessagesV1.scala
  webapi/src/main/scala/org/knora/webapi/messages/v1/responder/valuemessages/ValueMessagesV1.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
  webapi/src/main/scala/org/knora/webapi/responders/v1/CkanResponderV1.scala
  webapi/src/main/scala/org/knora/webapi/responders/v1/ResourcesResponderV1.scala
  webapi/src/main/scala/org/knora/webapi/responders/v1/StandoffResponderV1.scala
  webapi/src/main/scala/org/knora/webapi/responders/v1/ValuesResponderV1.scala
  webapi/src/main/scala/org/knora/webapi/responders/v2/ResourceUtilV2.scala
  webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
  webapi/src/main/scala/org/knora/webapi/responders/v2/StandoffResponderV2.scala
  webapi/src/main/scala/org/knora/webapi/routing/RouteUtilV1.scala
  webapi/src/main/scala/org/knora/webapi/routing/v1/ResourcesRouteV1.scala
  webapi/src/main/scala/org/knora/webapi/routing/v1/ValuesRouteV1.scala
  webapi/src/main/scala/org/knora/webapi/settings/KnoraSettings.scala
  webapi/src/main/scala/org/knora/webapi/store/iiif/SipiConnector.scala
  webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/addValueVersion.scala.txt
  webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/generateInsertStatementsForCreateValue.scala.txt
  webapi/src/test/scala/org/knora/webapi/e2e/v1/SipiV1R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/StringFormatterSpec.scala
  webapi/src/test/scala/org/knora/webapi/responders/IriLockerSpec.scala
  webapi/src/test/scala/org/knora/webapi/responders/v1/ResourcesResponderV1Spec.scala
  webapi/src/test/scala/org/knora/webapi/responders/v1/ResourcesResponderV1SpecContextData.scala
  webapi/src/test/scala/org/knora/webapi/responders/v1/ResourcesResponderV1SpecFullData.scala
  webapi/src/test/scala/org/knora/webapi/responders/v1/ValuesResponderV1Spec.scala
  webapi/src/test/scala/org/knora/webapi/store/iiif/MockSipiConnector.scala
Labels: API/V1, breaking, enhancement

#1727 DSP-740 Update List Name
  docs/03-apis/api-admin/lists.md
  docs/05-internals/development/generating-client-test-data.md
  webapi/scripts/expected-client-test-data.txt
  webapi/src/main/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADM.scala
  webapi/src/main/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesUtilADM.scala
  webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/ListsRouteADM.scala
  webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/updateListInfo.scala.txt
  webapi/src/test/scala/org/knora/webapi/e2e/admin/ListsADME2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADMSpec.scala
  webapi/src/test/scala/org/knora/webapi/responders/admin/ListsResponderADMSpec.scala
Labels: API/Admin, breaking, enhancement

#1728 fix(api-v2): Fix post-update check for resource with standoff link (DSP-841)
  docs/05-internals/development/generating-client-test-data.md
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
  webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
  webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
Labels: API/V2, bug

#1733 DSP-470 Intermittent bind errors
  webapi/src/main/scala/org/knora/webapi/app/ApplicationActor.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/BUILD.bazel
Labels: bug

#1736 DSP-877 Upload api-client-test-data to GitHub release
  .github/pull_request_template.md
  .github/workflows/main.yml
Labels: chore, clientapi

#1738 DSP-877 Upload api-client-test-data to GitHub release
  .github/workflows/main.yml
Labels: chore

#1740 DSP-877 Upload api-client-test-data to GitHub release
  .github/workflows/main.yml
Labels: chore

#1737 DSP-842 Bump used Bazel version to newly released 3.7.0
  .bazelrc
  .bazelversion
  .editorconfig
Labels: chore

#1739 enhancement(api-v2): Optimise checking isDeleted (DSP-848)
  webapi/src/main/scala/org/knora/webapi/messages/util/search/SparqlTransformer.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/AbstractPrequeryGenerator.scala
  webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/getGraphDataStandard.scala.txt
  webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/getResourcesInProjectPrequeryStandard.scala.txt
  webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/searchFulltextStandard.scala.txt
  webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/searchResourceByLabelStandard.scala.txt
  webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/searchResourceByLabelSubQuerySelectStandard.scala.txt
  webapi/src/test/scala/org/knora/webapi/e2e/v2/SearchRouteV2R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/search/SparqlTransformerSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/search/gravsearch/prequery/NonTriplestoreSpecificGravsearchToPrequeryTransformerSpec.scala
Labels: API/V2, Gravsearch, enhancement

#1734 feat(api-v2): Add metadata routes (DSP-662)
  docs/03-apis/api-v2/metadata.md
  docs/05-internals/design/api-v2/json-ld.md
  webapi/src/main/scala/org/knora/webapi/app/ApplicationActor.scala
  webapi/src/main/scala/org/knora/webapi/exceptions/Exceptions.scala
  webapi/src/main/scala/org/knora/webapi/messages/BUILD.bazel
  webapi/src/main/scala/org/knora/webapi/messages/StringFormatter.scala
  webapi/src/main/scala/org/knora/webapi/messages/admin/responder/projectsmessages/ProjectsMessagesADM.scala
  webapi/src/main/scala/org/knora/webapi/messages/store/triplestoremessages/TriplestoreMessages.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/JsonLDUtil.scala
  webapi/src/main/scala/org/knora/webapi/messages/util/RdfFormatUtil.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/KnoraRequestV2.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/KnoraResponseV2.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/listsmessages/ListsMessagesV2.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/metadatamessages/MetadataMessagesV2.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/ontologymessages/OntologyMessagesV2.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/ResourceMessagesV2.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/searchmessages/SearchMessagesV2.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/standoffmessages/StandoffMessagesV2.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
  webapi/src/main/scala/org/knora/webapi/responders/BUILD.bazel
  webapi/src/main/scala/org/knora/webapi/responders/ResponderManager.scala
  webapi/src/main/scala/org/knora/webapi/responders/admin/ProjectsResponderADM.scala
  webapi/src/main/scala/org/knora/webapi/responders/v2/MetadataResponderV2.scala
  webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala
  webapi/src/main/scala/org/knora/webapi/routing/BUILD.bazel
  webapi/src/main/scala/org/knora/webapi/routing/KnoraRoute.scala
  webapi/src/main/scala/org/knora/webapi/routing/RouteUtilV2.scala
  webapi/src/main/scala/org/knora/webapi/routing/v2/MetadataRouteV2.scala
  webapi/src/main/scala/org/knora/webapi/store/triplestore/http/GraphProtocolAccessor.scala
  webapi/src/main/scala/org/knora/webapi/store/triplestore/http/HttpTriplestoreConnector.scala
  webapi/src/main/scala/org/knora/webapi/util/SparqlUtil.scala
  webapi/src/test/scala/org/knora/webapi/CoreSpec.scala
  webapi/src/test/scala/org/knora/webapi/E2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/R2RSpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/e2e/v2/MetadataRouteV2E2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/messages/util/JsonLDUtilSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/KnoraResponseV2Spec.scala
  webapi/src/test/scala/org/knora/webapi/messages/util/RdfFormatUtilSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/v2/responder/metadatamessages/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/messages/v2/responder/metadatamessages/MetadataMessagesV2Spec.scala
  webapi/src/test/scala/org/knora/webapi/responders/v2/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/responders/v2/MetadataResponderV2Spec.scala
  webapi/src/test/scala/org/knora/webapi/sharedtestdata/SharedTestDataADM.scala
  webapi/src/test/scala/org/knora/webapi/store/triplestore/AllTriplestoreSpec.scala
Labels: API/V2, enhancement

#1743 chore(build): Upgrade Sipi to 3.0.0-rc.8 (DSP-916)
  Makefile
  third_party/versions.bzl
Labels: chore, dependencies

#1741 DSP-804: create a child node with a custom IRI
  docs/03-apis/api-admin/lists.md
  webapi/scripts/expected-client-test-data.txt
  webapi/src/main/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADM.scala
  webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
  webapi/src/test/scala/org/knora/webapi/e2e/admin/ListsADME2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADMSpec.scala
Labels: API/Admin, enhancement

#1744 DSP-917 Releases pushed to Dockerhub from DSP-API are "dirty"
  .github/workflows/main.yml
  docs/Readme.md
Labels: bug

#1745 chore(build): Update ScalaTest (DSP-919)
  salsah1/BUILD.bazel
  salsah1/src/test/scala/org/knora/salsah/BUILD.bazel
  third_party/dependencies.bzl
  webapi/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/messages/util/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/messages/v1/responder/permissionmessages/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/messages/v1/responder/usermessages/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/responders/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/store/triplestore/upgrade/plugins/BUILD.bazel
Labels: chore

#1746 DSP-932: Don't allow missing StringLiteralV2 value if language tag given
  webapi/src/main/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADM.scala
  webapi/src/main/scala/org/knora/webapi/messages/store/triplestoremessages/TriplestoreMessages.scala
  webapi/src/test/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADMSpec.scala
  webapi/src/test/scala/org/knora/webapi/messages/store/triplestoremessages/TriplestoreMessagesSpec.scala
Labels: bug
