Repository dasch-swiss/dsp-api, pull requests merged in 2020-08, with the labels that each got.

#1686 feat(api-v2): Accept custom timestamps in update/delete requests
  docs/03-apis/api-v2/editing-resources.md
  docs/03-apis/api-v2/editing-values.md
  webapi/src/main/scala/org/knora/webapi/messages/util/JsonLDUtil.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/resourcemessages/ResourceMessagesV2.scala
  webapi/src/main/scala/org/knora/webapi/messages/v2/responder/valuemessages/ValueMessagesV2.scala
  webapi/src/main/scala/org/knora/webapi/responders/v2/ResourcesResponderV2.scala
  webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
  webapi/src/main/scala/org/knora/webapi/routing/v2/ResourcesRouteV2.scala
  webapi/src/main/scala/org/knora/webapi/routing/v2/ValuesRouteV2.scala
  webapi/src/main/scala/org/knora/webapi/sharedtestdata/SharedTestDataADM.scala
  webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v2/getDeleteDate.scala.txt
  webapi/src/test/scala/org/knora/webapi/e2e/v2/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/e2e/v2/ResourcesRouteV2E2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/v2/ValuesRouteV2E2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/responders/v2/ResourcesResponderV2Spec.scala
  webapi/src/test/scala/org/knora/webapi/responders/v2/ValuesResponderV2Spec.scala
Labels: API/V2

#1689 build: bump SIPI to v3.0.0-rc.5 (DSP-547)
  third_party/versions.bzl
Labels: enhancement

#1691 fix: server header (DSP-537)
  third_party/dependencies.bzl
  tools/buildstamp/BUILD.bazel
  tools/version_info/BUILD.bazel
  tools/version_info/VersionInfoTemplate.scala
  tools/version_info/add_build_tag.sh
  tools/version_info/gen_version_info.bzl
  webapi/BUILD.bazel
  webapi/src/main/scala/org/knora/webapi/http/version/BUILD.bazel
  webapi/src/main/scala/org/knora/webapi/http/version/ServerVersion.scala
  webapi/src/main/scala/org/knora/webapi/instrumentation/BUILD.bazel
  webapi/src/main/scala/org/knora/webapi/routing/BUILD.bazel
  webapi/src/test/resources/logback-test.xml
  webapi/src/test/scala/org/knora/webapi/http/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/http/ServerVersionE2ESpec.scala
Labels: bug
