Repository dasch-swiss/dsp-api, pull requests merged in 2021-04, with the labels that each got.

#1840 feature(ext search v1): add support for Geoname values (DSP-1493)
  docs/03-apis/api-v1/reading-and-searching-resources.md
  webapi/src/main/scala/org/knora/webapi/responders/v1/SearchResponderV1.scala
  webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/searchExtendedGraphDB.scala.txt
  webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/searchExtendedStandard.scala.txt
  webapi/src/test/scala/org/knora/webapi/e2e/v1/SearchV1R2RSpec.scala
Labels: API/V1, user requirement

#1842 feat(ext search v1): add support for URI values (DSP-1522)
  docs/03-apis/api-v1/reading-and-searching-resources.md
  webapi/src/main/scala/org/knora/webapi/responders/v1/SearchResponderV1.scala
  webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/searchExtendedGraphDB.scala.txt
  webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/v1/searchExtendedStandard.scala.txt
  webapi/src/test/scala/org/knora/webapi/e2e/v1/SearchV1R2RSpec.scala
Labels: enhancement

#1848 docs(v1): improve search docs (DSP-1553)
  docs/03-apis/api-v1/reading-and-searching-resources.md
  docs/08-lucene/index.md
Labels: documentation

#1843 fix(test-data): change webern shortcode in test data (DSP-1520)
  test_data/all_data/admin-data.ttl
  test_data/all_data/permissions-data.ttl
  test_data/all_data/webern-data.ttl
  test_data/ontologies/webern-onto.ttl
  test_data/ontologyR2RV2/allOntologyMetadata.jsonld
  test_data/ontologyR2RV2/allOntologyMetadata.rdf
  test_data/ontologyR2RV2/allOntologyMetadata.ttl
  test_data/project_shortcodes.md
  test_data/queries/webern/find_webern_person.rql
  test_data/queries/webern/relation_via_schoenberg.rql
  webapi/scripts/fuseki-init-knora-test-unit.sh
  webapi/scripts/fuseki-init-knora-test.sh
  webapi/scripts/graphdb-knora-prod-data.expect
  webapi/scripts/graphdb-knora-test-data.expect
  webapi/scripts/win-graphdb-knora-test-data.ttl
  webapi/src/main/resources/application.conf
  webapi/src/test/scala/org/knora/webapi/CoreSpec.scala
  webapi/src/test/scala/org/knora/webapi/E2ESpec.scala
  webapi/src/test/scala/org/knora/webapi/e2e/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/e2e/admin/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/e2e/admin/lists/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/e2e/v1/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/e2e/v2/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/it/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/it/v1/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/other/v1/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/other/v2/BUILD.bazel
  webapi/src/test/scala/org/knora/webapi/sharedtestdata/SharedOntologyTestDataADM.scala
  webapi/src/test/scala/org/knora/webapi/sharedtestdata/SharedTestDataV1.scala
Labels: bug

#1846 fix(lists): Escape special characters in comment, label, and name of a list node (DSP-1529)
  webapi/src/main/scala/org/knora/webapi/messages/StringFormatter.scala
  webapi/src/main/scala/org/knora/webapi/messages/admin/responder/listsmessages/ListsMessagesADM.scala
  webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/lists/NewListsRouteADMFeature.scala
  webapi/src/main/scala/org/knora/webapi/routing/admin/lists/OldListsRouteADMFeature.scala
  webapi/src/test/scala/org/knora/webapi/responders/admin/ListsResponderADMSpec.scala
Labels: API/Admin, bug
